SELECT CLIENT_ID, DATEDIFF('MONTH', START_DATE, FINISH_DATE) AS TIME
FROM PROJECT
WHERE DATEDIFF('MONTH', START_DATE, FINISH_DATE) = (
    SELECT MAX(DATEDIFF('MONTH', START_DATE, FINISH_DATE)) FROM PROJECT
    )