SELECT NAME, COUNT(p.ID) as PROJECT_COUNT
FROM CLIENT c
JOIN PROJECT p ON c.ID = p.CLIENT_ID
GROUP BY c.ID, c.NAME
HAVING COUNT(p.ID) = (
    SELECT MAX(PROJECTCOUNT)
    FROM (SELECT COUNT(ID) AS PROJECTCOUNT
          FROM PROJECT
          GROUP BY CLIENT_ID)
    )