CREATE TABLE IF NOT EXISTS worker(
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK(LENGTH(NAME) >= 2),
    BIRTHDAY DATE CHECK(YEAR(BIRTHDAY) >= 1900),
    LEVEL VARCHAR(10) NOT NULL CHECK(LEVEL IN('Trainee', 'Junior', 'Middle', 'Senior')),
    SALARY INT CHECK(100 < SALARY AND SALARY < 100000)
    );

CREATE TABLE IF NOT EXISTS client(
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK(LENGTH(NAME) >= 2)
    );

CREATE TABLE IF NOT EXISTS project(
    ID IDENTITY PRIMARY KEY,
    CLIENT_ID BIGINT NOT NULL,
    START_DATE DATE,
    FINISH_DATE DATE,
    CONSTRAINT CLIENT_ID_DK FOREIGN KEY(CLIENT_ID) REFERENCES client(ID)
    );

CREATE TABLE IF NOT EXISTS project_worker(
    PROJECT_ID BIGINT NOT NULL,
    WORKER_ID BIGINT NOT NULL,
    PRIMARY KEY(PROJECT_ID, WORKER_ID),
    CONSTRAINT PROJECT_ID_DK FOREIGN KEY (PROJECT_ID) REFERENCES project(ID),
    CONSTRAINT WORKER_ID_DK FOREIGN KEY (WORKER_ID) REFERENCES worker(ID)
    );
